# Site settings
title: TUD | The Underground Dragons
description: "A Tor based Social Network."
url: "http://undergrounddragons.github.io/"
author:
  name: "Matheus Borges Teixeira"
  email: "matheus.bt@gmail.com"
  url: "http://github.com/matheuscodes"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page/:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.0.1"

# Options
# custom_header: false
# custom_nav_footer: false
reverse: false
highlighter: null
